"""
    Problem Statement: 
        You are given two strings s and t
        String t is generated by "RANDOM SHUFFING" string s and then add one more letter at a random position.
        Return the letter that was added to t.
        
    Example 1:
        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.
        
    Example 2:
        Input: s = "", t = "y"
        Output: "y"

    Constraints:
        * 0 <= s.length <= 1000
        * t.length == s.length + 1
        * s and t consist of lowercase English letters.
"""
from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
            Simply convert string to look up dictionary
        """
        s_freq = Counter(s)
        t_freq = Counter(t)
        
        for char, freq in t_freq.items():
            tmp = s_freq.get(char, -1)
            if tmp == -1 or tmp != freq:
                return char
            

if __name__ == '__main__':
    s = Solution()
    print(s.findTheDifference(s="abcd", t="abcde"))
    print(s.findTheDifference(s="", t="y"))
    